var list = ["Laiba", "Mannu", "Hassan"];
list[1] = "Umair";
console.log("ALright, so I found a bigger dinning table.");
list.push("Raheem", "Afridi", "Mary");
console.log("now: ");
console.log("I would love to invite " + list[0]);
console.log("I would love to invite " + list[1]);
console.log("I wolud love to invite " + list[2]);
console.log("I would love to invite " + list[3]);
console.log("I would love to invite " + list[4]);
